"""empty message

Revision ID: 76036c05e51b
Revises: e673ac0153c2
Create Date: 2025-10-18 14:29:20.841596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76036c05e51b'
down_revision = 'e673ac0153c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
